### ISSUE TITLE
Systemd service (RH8/Centos8)

### ISSUE THREAD

**Issue by RaNd250** [Incognito/one-time-secret#337]
Below is my systemd config
The install path is opt/one-time-secret/

create     /lib/systemd/system/ots.service

`nano /lib/systemd/system/ots.service`
`systemctl daemon-reload`
`systemctl start ots`

`[Unit]
Description=OneTimeSecret Service
After=network.target

[Service]
Environment=PUBLISH_SECRET_URI='/'
Environment=KEY_NAME_RANDOM_BYTES=32
Environment=PORT=80
Environment=DOMAIN=ots.example.com
Environment=HTTP_TIMEOUT_MS=5000
Environment=MAX_UPLOAD_KB=128

Type=simple
ExecStart=/usr/bin/node /opt/one-time-secret/dist/bin/cli.js web:start
Restart=on-failure

[Install]
WantedBy=multi-user.target`

**Comment by Incognito** [comment]
Thanks for the contribution, this will make it into the Wiki next time I sweep through and do updates :+1:

**Comment by Incognito** [comment]
Thanks again, I've added it to the wiki

https://github.com/Incognito/one-time-secret/wiki/Setup:-Adding-to-systemd
